export const Talukas = [
    {
        id:1,
        name:"जावळी",
        hospitals :[{
            id:4,
            name:"BCJ",
            location:"जावळी",
            mobile_no:"75438652874"
        },
        {
            id:5,
            name:"BCE",
            location:"जावळी",
            mobile_no:"75438652874"
        },
        {
            id:6,
            name:"BC",
            location:"जावळी",
            mobile_no:"75438652874"
        }]
    },
    {
        id:2,
        name:"कराड",
        hospitals : [
            {
                id:7,
                name:"BC1",
                location:"कराड",
                mobile_no:"75438652874"
            },
            {
                id:8,
                name:"BC1",
                location:"कराड",
                mobile_no:"75438652874"
            },
            {
                id:9,
                name:"BC1",
                location:"कराड",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:3,
        name:"खंडाला",
        hospitals :[
            {
                id:10,
                name:"BC1",
                location:"खंडाला",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:4,
        name:"खटाव",
        hospitals :[
            {
                id:11,
                name:"BC1",
                location:"खटाव",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:5,
        name:"कोरेगाव",
        hospitals :[
            {
                id:12,
                name:"BC1",
                location:"कोरेगाव",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:6,
        name:"महाबळेश्वर",
        hospitals :[
            {
                id:13,
                name:"BC1",
                location:"महाबळेश्वर",
                mobile_no:"75438652874"
            },
            {
                id:14,
                name:"BC1",
                location:"महाबळेश्वर",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:7,
        name:"माण",
        hospitals :[
            {
                id:20,
                name:"BC1",
                location:"माण",
                mobile_no:"75438652874"
            },
            {
                id:21,
                name:"BC1",
                location:"माण",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:8,
        name:"पाटण",
        hospitals :[
            {
                id:15,
                name:"BC1",
                location:"पाटण",
                mobile_no:"75438652874"
            },
            {
                id:16,
                name:"BC1",
                location:"पाटण",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:9,
        name:"फलटण",
        hospitals :[
            {
                id:22,
                name:"BC1",
                location:"फलटण",
                mobile_no:"75438652874"
            },
            {
                id:23,
                name:"BC1",
                location:"फलटण",
                mobile_no:"75438652874"
            },
        ]
    },
    {
        id:10,
        name:"सातारा",
        hospitals: [
            {
                id:1,
                name:"ABC",
                location:"सातारा",
                mobile_no:"75438652874"
            },
            {
                id:2,
                name:"BC",
                location:"सातारा",
                mobile_no:"75438652874"
            },
            {
                id:3,
                name:"BCA",
                location:"सातारा",
                mobile_no:"75438652874"
            },
        ]

    },
    {
        id:11,
        name:"वाई",
        hospitals :[
            {
                id:17,
                name:"BC1",
                location:"वाई",
                mobile_no:"75438652874"
            },
            {
                id:18,
                name:"BC1",
                location:"वाई",
                mobile_no:"75438652874"
            },
        ]
    }

]